### ISSUE TITLE
Can't connect with unrechable network

### ISSUE THREAD

**Issue by antonioriva** [PinBack23/nonkyo#1]
I have a VirtualBox virtual network, NOnkio fail without finding a network.

I've found a problem in nonkyo\src\nonkyo.iscp\devicesearch.cs

When searching for broadcast addresses:
```
foreach (var loBroadcast in loIPAddressList)
{
    Logger.Debug("Find Broadcastaddress {0}", loBroadcast);
    loSendUdp.Send(loCommand, loCommand.Length, loBroadcast.ToString(), pnPort);
}
```

an exception is thrown if the network in unrechable, but if it's the first one no interface is added to the list. Try Catchiong the Send instruction keep other network reachable
```
foreach (var loBroadcast in loIPAddressList)
{
    try
    {
        Logger.Debug("Find Broadcastaddress {0}", loBroadcast);
        loSendUdp.Send(loCommand, loCommand.Length, loBroadcast.ToString(), pnPort);
    }
    catch( Exception exp)
    {
        Logger.Log(NLog.LogLevel.Error, "Failed", exp);
    }
}
```

I cannot compile the git code with VS2015 community... this is why I've not forked/pulled the modification. Is VS2012 needend again?

**Comment by PinBack23** [comment]
Thanks for your suggestion.
I've changed the code.

I have also VS2015 (but the enterprise version).
Perhaps you are missing the installation of WiX Toolset (Version 3.10).
